Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ap-south-1a
      ImageId: ami-07d3a50bd29811cd1
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref MySecurityGroup1
        - !Ref MySecurityGroup2
  

  MySecurityGroup1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: My Security Group 1
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  
  MySecurityGroup2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: My Security Group 2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  
  MyEBSVolume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: !GetAtt MyEC2Instance.AvailabilityZone
      VolumeType: io1
      Size: 10
      Iops: 100
  
  MountPoint:
    Type: AWS::EC2::VolumeAttachment
    Properties: 
      Device: /dev/sdh
      InstanceId: !Ref MyEC2Instance
      VolumeId: !Ref MyEBSVolume


